
all:OTP caesar vigenere clean

OTP:test_1.c
	gcc test_1.c -o otp
	./otp

caesar:test_2.c
	gcc test_2.c -o caesar
	./caesar

vigenere:test_3.c
	gcc test_3.c -o vigenere
	./vigenere

clean:
	rm otp
	rm caesar
	rm vigenere
